// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/div",
				Handler: DivHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/greet/from/:name",
				Handler: GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mul",
				Handler: MulHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sub",
				Handler: SubHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sum",
				Handler: SumHandler(serverCtx),
			},
		},
	)
}
